services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - "wordpress-data:/var/www/wordpress"
    networks:
      - inception
    restart: on-failure
    secrets:
      - ssl_key
      - ssl_crt
    ports:
        - "443:443"
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure
    volumes:
      - "wordpress-data:/var/www/wordpress"
    networks:
      - inception
    ports:
      - "9000"

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - "mariadb-data:/var/lib/mysql"
    networks:
      - inception
    restart: unless-stopped
    expose:
      - "3306"

networks:
  inception:
    name: inception

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/agerbaud/data/wordpress'
  mariadb-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/agerbaud/data/mariadb'

secrets:
  ssl_key:
    file: "../.SECRET/private_key.key"
  ssl_crt:
    file: "../.SECRET/certificate.crt"
